version: "3.8"

services:
  api:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "10242:10242"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 10242
